package com.bartoszosipiuk.pos.device.input;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Created by Bartosz Osipiuk on 2018-03-16.
 *
 * @author Bartosz Osipiuk
 */

public class BarcodeScanner implements Scanner {
    private List<BarcodeScanListener> listeners;

    public BarcodeScanner() {
        this.listeners = new ArrayList<>();
    }

    public void addListener(BarcodeScanListener barcodeScanListener){
        listeners.add(barcodeScanListener);
    }

    @Override
    public void scanBarcode() {
        //todo: Connect device and use received code;
        //Now we are using autogenerated barcode
        String codeFromBarcode = String.valueOf(ThreadLocalRandom.current().nextInt(9999-99999))+"ABC";
        listeners.forEach(listener -> listener.onBarcodeScan(codeFromBarcode));
    }
}
